config/routes.rb
Rails.application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'index#index'

  # delete '/block_lists/:id/remove/blocker/:user_id' => 'block_lists#remove_blocker', :as => :remove_blocker
  resources :block_lists, except: :show
  get    '/block_lists/:id'              => 'block_lists#show', :constraints => { :id => /[0-9]+/ }, :as => :block_list_path
  get    '/block_lists/:name'            => 'block_lists#show'
  post   '/block_lists/:id/add/blocker/' => 'block_lists#add_blocker', :as => :add_blocker
  post   '/block_lists/:id/add/admin/'   => 'block_lists#add_admin',   :as => :add_admin
  post   '/block_lists/:id/subscribe'    => 'block_lists#subscribe',   :as => :list_subscribe
  delete '/block_lists/:id/subscribe'    => 'block_lists#unsubscribe', :as => :list_unsubscribe

  post   'reports/:id/approve' => 'reports#approve', :as => :report_approve
  get    'reports/new'         => 'reports#new',     :as => :report_new
  get    'reports/:id'         => 'reports#show',    :as => :report
  delete 'reports/:id'         => 'reports#deny',    :as => :report_deny
  post   'reports'             => 'reports#create',  :as => :report_create
  get    'reports'             => 'reports#index',   :as => :reports

  get 'tools/test' => 'tools#test'
  get 'tools/hunkerdown' => 'tools#hunkerdown'
  get 'tools/blockchain' => 'tools#blockchain'

  get  '/signin'                  => 'sessions#new',      :as => :signin
  get  '/signout'                 => 'sessions#destroy',  :as => :signout
  get  '/auth/failure'            => 'sessions#failure'
  get  '/auth/:provider/callback' => 'sessions#create'

  get '/profile' => 'users#index', :as => :profile
  get '/user/reports' => 'users#reports', :as => :user_reports

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/block_list.rb
class BlockList < ActiveRecord::Base
  has_many :reports
  has_many :blocks

  has_many :subscriptions
  has_many :users, through: :subscriptions

  has_many :active_reports, -> { where(approved: true, expired: false) }, class_name: Report
  has_many :targets, through: :active_reports

  has_many :admin_records, class_name: Admin, dependent: :destroy
  has_many :admins, through: :admin_records, source: :user, dependent: :destroy

  has_many :blocker_records, class_name: Blocker, dependent: :destroy
  has_many :blockers, through: :blocker_records, source: :user, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  def blocker?(user)
    user.in? self.blockers
  end

  def admin?(user)
    user.in? self.admins
  end

  def blocker_autoapprove?(user)
    (self.autoapprove_blocker?) and (self.blocker? user)
  end

  def admin_autoapprove?(user)
    (self.autoapprove_admin?) and (self.admin? user)
  end

  def self.where_blocker(user)
    self.joins(:blocker_records).where(:blockers => {user_id: user.id})
  end

  def self.where_admin(user)
    self.joins(:admin_records).where(:admins => {user_id: user.id})
  end

  def self.make(name, user)
    block_list = self.create(:name => name)
    Admin.create(block_list: block_list, user: user)
    return block_list
  end

  def self.get_expiration(block_list)
    block_list.expires ? DateTime.now + block_list.expires : nil
  rescue NoMethodError
    nil
  end

  def self.find_by_name(name)
    name = MetaTwitter.strip_if_leading_character(name, '#')
    self.where("replace(lower(name), ' ', '') = ?", name.downcase).first
  end

end

app/controllers/block_lists_controller.rb
class BlockListsController < ApplicationController
  before_action :set_block_list

  # GET /block_lists
  def index
    @block_lists = BlockList.all
  end

  # GET /block_lists/1
  def show
  end

  # GET /block_lists/new
  def new
    if current_user
      @block_list = BlockList.new
    else
      redirect_to '/'
    end
  end

  # POST /block_list
  def create
    if current_user
      @block_list = BlockList.make(block_list_params['name'], current_user)

      respond_to do |format|
        if @block_list.save
          format.html { redirect_to block_list_url(@block_list), notice: 'Block List created' }
        else
          format.html { render :new }
        end
      end
    else
      redirect_to :back
    end
  end

  # PATCH/PUT /block_lists/1
  def update
    if @block_list.admin? current_user
      respond_to do |format|
        if @block_list.update(block_list_params)
          format.html { redirect_to @block_list, notice: 'Block list was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  # POST /block_lists/1/subscribe
  def subscribe
    if current_user
      Subscription.add(current_user, @block_list)

      respond_to do |format|
        format.html { redirect_to :back, notice: 'Subscribed to '+@block_list.name}
      end

    else
      redirect_to :back
    end
  end

  # DELETE /block_lists/1/subscribe
  def unsubscribe
    if current_user
      Subscription.remove(current_user, @block_list)

      respond_to do |format|
        format.html { redirect_to :back, notice: 'Unsubscribed from '+@block_list.name}
      end

    else
      redirect_to :back
    end
  end

  # POST /block_lists/1/add/blocker
  def add_blocker
    if @block_list.admin? current_user
      blocker = Blocker.create(block_list: @block_list, user: User.get_from_twitter_name(params[:user_name]))

      if blocker.save
        notice = "Blocker #{params[:user_name]} added"
      else
        notice = blocker.errors.full_messages
      end

      redirect_to :back, notice: notice
    else
      redirect_to :back, notice: 'Not authorized'
    end
  end

  # POST /block_lists/1/add/admin
  def add_admin
    if @block_list.admin? current_user
      admin = Admin.create(block_list: @block_list, user: User.get_from_twitter_name(params[:user_name]))

      if admin.save
        notice = "Admin #{params[:user_name]} added"
      else
        notice = admin.errors.full_messages
      end

      redirect_to :back, notice: notice
    else
      redirect_to :back, notice: 'Not authorized'
    end
  end

  # def remove_blocker
  #   Blocker.find_by(block_list: @block_list, user: User.find(params[:user_id])).delete
  #   redirect_to :back, notice: 'Blocker removed'
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block_list
      if params[:id]
        @block_list = BlockList.find(params[:id])
      elsif params[:name]
        @block_list = BlockList.where("lower(name) = ?", params[:name].downcase).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_list_params
      params.require(:block_list).permit(:name)
    end
end

app/views/block_lists/_form.html.haml
= form_for @block_list, :html => { :class => "form-horizontal block_list" } do |f|
  - if @block_list.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@block_list.errors.count, "error")
          prohibited this block_list from being saved:
      .panel-body
        %ul
          - @block_list.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        block_lists_path, :class => 'btn btn-default'                |

app/views/block_lists/edit.html.haml
- model_class = BlockList
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/block_lists/index.html.haml
- model_class = BlockList
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
  %p Only showcased block lists are listed here, individual block lists are accessed through their url
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Hashtag
      %th Description
      %th Subscribers
      %th Blockers
      %th Blocked Users
      %th Actions
  %tbody
    - @block_lists.where(showcase: true).each do |block_list|
      %tr
        %td= link_to block_list.name, block_list_path(block_list)
        %td= '#'+block_list.name.downcase.delete(' ')
        %td= block_list.description
        %td= block_list.users.length
        %td= block_list.blockers.length
        %td= block_list.targets.length
        %td
          - if current_user.in? block_list.users
            = button_to 'Unsubscribe + Remove Blocks',
              list_unsubscribe_path(block_list),
              :method => :delete,
              :class => 'btn btn-sm btn-danger'
          - else
            = button_to 'Subscribe',
              list_subscribe_path(block_list),
              :method => :post,
              :class => 'btn btn-sm btn-primary'

= link_to 'Create new Block List',
  '/block_lists/new', :class => 'btn btn-default'

app/views/block_lists/new.html.haml
- model_class = BlockList
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/block_lists/show.html.haml
- model_class = BlockList
.page-header
  %h1= @block_list.name
  %p= @block_list.description
  - if current_user.in? @block_list.users
    = link_to 'Unsubscribe + Remove Blocks',
      list_unsubscribe_path(@block_list),
      :method => :delete,
      :class => 'btn btn-danger'
  - else
    = link_to 'Subscribe',
      list_subscribe_path(@block_list),
      :method => :post,
      :class => 'btn btn-primary'

%dl.dl-horizontal
  %dt
    %strong Subscribers:
  %dd= @block_list.users.length
  - if @block_list.admins.length > 0
    %dt
      %strong Admins:
    - for admin in @block_list.admins
      %dd= link_to "#{admin.name} (@#{admin.user_name})", "http://#{admin.website}.com/#{admin.user_name}"
  - if (@block_list.blockers - @block_list.admins).length > 0
    %dt
      %strong Blockers:
    - for blocker in (@block_list.blockers - @block_list.admins)
      %dd= link_to "#{blocker.name} (@#{blocker.user_name})", "http://#{blocker.website}.com/#{blocker.user_name}"
  %dt
    %strong Blocked Users:
  %dd= @block_list.targets.length
  - if @block_list.blocker? current_user
    %br
    %dt
      %strong Pending Reports:
    %dd= link_to @block_list.reports.where(processed: false).length, '/reports'
    %dt
      %strong Active Blocks:
    %dd= @block_list.blocks.length

%dl.dl-horizontal
  - if @block_list.admin? current_user
    = form_tag add_blocker_path(@block_list), :method => 'post' do
      %dt= submit_tag "Add Blocker", :class => 'btn btn-primary btn-sm'
      %dd= text_field_tag :user_name, nil, :placeholder => "@name, like @lynncyrin"
    = form_tag add_admin_path(@block_list), :method => 'post' do
      %dt= submit_tag "Add Admin", :class => 'btn btn-primary btn-sm'
      %dd= text_field_tag :user_name, nil, :placeholder => "@name, like @lynncyrin"

%h2 Blocked Users
%table.table.table-striped
  %thead
    %tr
      %th Username
      %th Profile Description
      %th Time Reported
      %th View Reports
  %tbody
    - @block_list.reports.where(approved: true, expired: false).each do |report|
      %tr
        %td= link_to "#{report.target.name} (@#{report.target.user_name})", "http://twitter.com/#{report.target.user_name}"
        %td= report.target.description
        %td= time_ago_in_words(report.created_at) + ' ago'
        %td= link_to 'Reports', "/user/reports/?id=#{report.target.id}", :class => 'btn btn-default'

= link_to 'Back to Block Lists',
  block_lists_path, :class => 'btn btn-default'
= link_to 'Create new Block List',
  '/block_lists/new', :class => 'btn btn-default'